#! /bin/bash
# send - sends files (grades)
#

EXITCODE=0

DIR=/afs/cats.ucsc.edu/class/cmps012b-pt.u14/pa5
#DIR=~/private/cs12b/bin/temp
FILE=grade

#
# iterates through directory list and checks if directory exist
#
for i in $(ls $DIR)
do
	if [ -d "${DIR}/$i" ]
	then
#
# sends files
#
		if [ -e "${DIR}/${i}/$FILE" ]
		then
			echo "sending mail to ${i}@ucsc.edu"
			cat ${DIR}/${i}/$FILE | mailx -s "CMPS-12B PA5 Grade" ${i}@ucsc.edu >& tmp
			sleep 10
			if [ -e tmp -a $(wc -l < tmp) -eq 0 ]
			then
				echo "mail to ${i} is sent"
			else
				echo "mail to ${i} is not sent"
				cat tmp
			fi
		else 
			echo "could not sent email to ${i}@ucsc.edu"
			echo "$FILE does not exist"
		fi	
     	else
#
# prints error message if directory does not exist
#
		echo "$i: directory does not exist" >&2
		echo
		EXITCODE=2
	fi
done
echo "all mails are sent"
exit $EXITCODE
